server:
  port: 10000
  forward-headers-strategy: framework

spring:
  application:
    name: genio

  config:
    import: optional:classpath:./credentials.properties

  datasource:
    url: jdbc:h2:file:./db/genio
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

clova:
  ocr:
    secret-key: ${CLOVA_OCR_SECRET_KEY}
    api-gateway-url: ${CLOVA_OCR_API_GATEWAY_URL}

  studio:
    api-key: ${CLOVA_STUDIO_API_KEY}
    base-url: ${CLOVA_STUDIO_BASE_URL}
    max-tokens: 2048
    temperature: 0.3
